name: Argos CI Screenshots

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  take-screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Install Playwright browsers
        run: npm installplaywright chromium

      - name: Build the website
        run: npm docusaurus build

      - name: Take screenshots with Playwright
        run: npm playwright test

      - name: Upload screenshots to Argos
        run: npm argos upload ./screenshots